name: Schedule jobs

on:
  schedule:
    - cron: "*/5 * * * *"   # Runs every 5 minutes (for testing)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "Schedule Workflow Executed"
